### ISSUE TITLE
How do I access the Strapi backend?

### ISSUE THREAD

**Issue by cmarabate** [jeremylynch/gatsby-strapi-starter#1]
Hello, I love this template but I'm a little confused about how it uses Strapi. 

I have it up and running at [https://adoring-elion-4cabfb.netlify.com](https://adoring-elion-4cabfb.netlify.com)

But I don't seem to be able to visit [https://adoring-elion-4cabfb.netlify.com/admin](https://adoring-elion-4cabfb.netlify.com/admin) to access the Strapi backend like I was expecting.

Isn't that the whole point of Strapi? There must be something I am missing, could you please clear things up for me?

Thanks,

Chris

**Comment by jeremylynch** [comment]
Hi Chris, you need to host Strapi separately with a server (ie like Digital Ocean, AWS). 

Check out the one-click deploy here: https://marketplace.digitalocean.com/apps/strapi
