### ISSUE TITLE
No response from develop server

### ISSUE THREAD

**Issue by bilogic** [jeremylynch/gatsby-strapi-starter#3]
Hi,

I cloned this project and ran ```npm i``` followed by ```gatsby develop```, there are no errors. However the browser keeps loading and finally timeout with no response from the develop server.

I have cloned other gatsby projects before, none have behaved like this. Is there a need to setup/config strapi or something?

Thank you.

**Comment by jeremylynch** [comment]
Can you please send a screenshot?

**Comment by bilogic** [comment]
So sorry, I have moved on. I will close this issue. Thank you.
